export const routeConstants = {
  root: "/", //
  login: "/login", //
  register: "/register", //
  dashboard: "/dashboard", //
  reports: "/reports",
  categories: "/categories",
  subCategories: "/sub-categories",
  menuAndProducts: "/menu-and-products",
  productReviews: "/product-reviews",
  recentOrders: "/recent-orders",
  orderHistory: "/order-history",
  orderDetails: "/orders/:orderId",
  createOrder: "/create-order",
  orderReviews: "/order-reviews",
  orderTickets: "/order-tickets",
  customerList: "/customers",
  createCustomer: "/create-customer",
  contactUseRequests: "/contact-us-requests",
  profileScreenRequests: "/profile-screen-requests",
  discounts: "/discounts",
  discountDetails: "/discounts/:action/:discountType/:discountId",
  staff: "/staff",
  staffDetails: "/staff/:action/:staffId",
  gallery: "/gallery",
  stores: "/stores",
  storesView: "/stores/view/:storeId",
  storesDetails: "/stores/:action/:storeId",
  deliveryBoyReviews: "/delivery-boy-reviews",
  websiteLogos: "/website-logs",
  paymentManagement: "/payment-management",
  extraCharges: "/extra-charges",
  deliveryCharges: "/delivery-charges",
  websiteAvailability: "/website-availability",
  banners: "/banners",
  policyPages: "/policy-pages",
  contactUsInfo: "/contact-us-info",
  account: "/account",
  addons: "/addons",
};
